### ISSUE TITLE
Add remaining Software

### ISSUE THREAD

**Issue by matthuska** [mf1-btr/mf1-btr.github.io#19]
The Software page is incomplete. Add remaining software from https://hoelzer.github.io/tools/ at least.

**Comment by hoelzer** [comment]
- [ ] RIBAP
- [ ] poreCov
- [ ] PoSeiDon
- [ ] Breakfast
- [ ] POCP-nf
- [ ] PCAGO
- [ ] RNAflow
- [ ] CLEAN
- [ ] VIRify
