### ISSUE TITLE
[New Member]: Hugues Richard

### ISSUE THREAD

**Issue by huguesrichard** [mf1-btr/mf1-btr.github.io#47]
### Name

Hugues Richard

### URL name

hugues-richard

### ORCID identifier

0000-0001-7776-1340

### Aliases

H Richard

### Bio

Hugues Richard is Senior Researcher and Principal Investigator. With a background in statistics and computational biology, he has been an Associate Professor at Sorbonne University since 2009 (Computer Science dept, currently on leave). His research focuses on statistical methods for high-throughput sequencing data and computational genomics. Dr. Richard's recent projects include creating tools for analyzing large-scale transcriptomic and metagenomics data, the analysis of bacterial pangenomes, and developing algorithms for the genomics of transplantation and the molecular diagnostics of pathogens.

### Socials

Google Scholar: TzNfNbYAAAAJ, former Sorbonne Webpage (not maintained much except CV): http://www.lcqb.upmc.fr/hrichard/index.html

### Agreement

- [X] Yes, I have signed the document and sent it to Martin

**Comment by matthuska** [comment]
@huguesrichard I think you were too fast when sending the little comment with your picture. Can you try again?
