### ISSUE TITLE
[New Member]: Daniel Desirò

### ISSUE THREAD

**Issue by desiro** [mf1-btr/mf1-btr.github.io#75]
### Name

Daniel Desirò

### URL name

daniel-desiro

### ORCID identifier

0000-0003-3928-9094

### Bio

I am Daniel, a bioinformatician interested in understanding the underlying mechanisms of viruses and other pathogens. My expertise lies primarily in predicting the RNA structure of viral RNAs and selective genome packaging of segmented RNA viruses such as rotavirus A and influenza A virus. In addition, I have a solid foundation in next-generation sequencing analysis, machine learning and statistical methods. 

I obtained my Master of Science in “Bioinformatics and Systems Biology” at the Albert-Ludwigs-University Freiburg in 2016 and subsequently completed my PhD at the Friedrich-Schiller-University Jena with a focus on RNA structure prediction and packaging of the influenza A virus. Following my PhD, I was able to expand my expertise in a three-year postdoctoral position at the University of Cambridge, where I continued my research on rotavirus A genome assembly. In particular, in the areas of experimental RNA structure detection by high-throughput sequencing using methods such as RNA cross-linking (SPLASH) and RNA mutation profiling (SHAPE-MaP) as well as in the field of viral protein prediction by liquid-liquid phase separation using machine learning. Since 2024, I have continued my academic journey as a postdoctoral researcher at the Genome Competence Center of the Robert Koch Institute (RKI) in Berlin, focusing on metagenomics in the context of public health.  

### Agreement

- [X] Yes, I have signed the document and sent it to Martin

**Comment by matthuska** [comment]
Closed by #77
